[build]
  base = "mern-client"  # Set the base directory to mern-client for frontend build
  publish = "mern-client/dist"  # Set the publish directory to mern-client/dist
  command = "npm run build"  # Run the build command in the mern-client folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
